name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false

      - name: Compliance check
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo ${{ steps.linter.outputs.checks-failed }} violations found
          exit 1
